dashboard/urls.py
from django.urls import path
from dashboard.views import dashboard

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name="index"),
]

piadda/urls.py
from django.contrib import admin
from django.urls import path, include

from dashboard.views import dashboard

urlpatterns = [
    path('', dashboard),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
# django
from django.shortcuts import render

# project
from dashboard.backends.ros2_channels.ros2_utils import list_ros2_topics

def dashboard(request):
    ctx = {'topics': list_ros2_topics()}
    return render(request, 'dashboard/piadda.html', ctx)

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8" />
  <!-- JQuery -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <!-- bootstrap css -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- bootstrap js -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>
  <!-- d3js -->
  <script src="https://d3js.org/d3.v4.js"></script>
  <!-- d3js -->
  <link href="{% static 'dashboard/css/sidebars.css' %}" rel="stylesheet">
  <title>piadda - piadda is another data dashboard attempt</title>
  <link rel="icon" type="image/x-icon" href="{% static 'dashboard/img/icons8-data-analytics-96.png' %}">
</head>

<body>
  {% block navbar %} {% include 'dashboard/navbar.html' %} {% endblock %}
  {% block content %} {% endblock %}
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center"></div>
    <div class="nav col-md-4 justify-content-end d-flex">
      <a target="_blank" href="https://icons8.com/icon/LgTN0AzFZcRJ/data-analytics">Data Analytics</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
    </div>
  </footer>
</body>

</html>

dashboard/templates/dashboard/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
    <a class="navbar-brand"><img src="{% static 'dashboard/img/icons8-data-analytics-96.png' %}" height="30" style="margin-left: 15px;"
            class="d-inline-block align-top" alt="piadda-Logo"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'dashboard:index' %}"> Home </a>
            </li>
        </ul>
    </div>
    <span class="navbar-text">
        piadda - piadda is another data dashboard attempt
    </span>
</nav>

dashboard/templates/dashboard/piadda.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'dashboard/js/modals.js' %}"></script>
<script src="{% static 'dashboard/js/draw_meter.js' %}"></script>
<script src="{% static 'dashboard/js/draw_timeseries.js' %}"></script>
<script src="{% static 'dashboard/js/draw_map.js' %}"></script>
<script src="{% static 'dashboard/js/piadda.js' %}"></script>
<link rel="stylesheet" href="{% static 'dashboard/css/one-style.css' %}?{% now 'U' %}" />
<main id="main">
  <div class="flex-shrink-0 p-3 bg-white" style="width: 320px;">
    <span class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom fs-5 fw-semibold">ROS2
      Topics</span>
    <ul class="list-unstyled ps-0">
      {% for topic in topics %}
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
          data-bs-target="#home-collapse{{forloop.counter}}">
          {{ topic.name }} - {{ topic.msg_types.0 }}
        </button>
        <div class="collapse" id="home-collapse{{forloop.counter}}">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            {% for key, values in topic.fields_tree.items %}
            {% for value in values %}
            <li>
              <input class="form-check-input topic-check-input" type="checkbox" value="{{value}}"
                id="field{{topic.name_html}}-{{value}}" data-topic="{{topic.name}}"
                data-msg-type="{{topic.msg_types.0}}">
              <label class="form-check-label" for="field{{topic.name_html}}-{{value}}">
                {{value}}
              </label>
            </li>
            {% endfor %}
            {% endfor %}
          </ul>
        </div>
      </li>
      {% endfor %}
    </ul>
    <div class="form-group mb-3">
      <button type="button" id="add_xymap" class="btn btn-primary">Add XY Map</button>
    </div>
    <div class="form-group mb-3">
      <button type="button" id="add_timeseries" class="btn btn-primary">Add Time Series</button>
    </div>
    <div class="form-group mb-3">
      <button type="button" id="add_meter" class="btn btn-primary">Add Meter</button>
    </div>
  </div>
  <div class="b-example-divider"></div>
  <div id="graphics" class="row">
  </div>
</main>
<script>
  $('#add_xymap').on('click', function () {
    const options = { 'showYAxis': true };
    processForm('map', options);
  });
  $('#add_timeseries').on('click', function () {
    const options = { 'showYAxis': true };
    processForm('series', options);
  });
  $('#add_meter').on('click', function () {
    const options = { 'maxDataLength': 10, 'height': 80, 'showYAxis': false };
    processForm('meter', options);
  });
</script>
{% endblock %}